name: Run Gas Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  set_keys_and_run_tests:
    name: Set API Keys and Run Gas Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gas tests
        run: npx hardhat test

    env:
      BSCSCAN_API_KEY: ${{ secrets.YOUR_BSCSCAN_API_KEY }}
      CMC_API_KEY: ${{ secrets.YOUR_CMC_API_KEY }}
