name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'  # Specify your Node.js version here

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check if cache hit
        id: cache-hit
        run: |
          if [ -d 'node_modules' ]; then
            echo "CACHE_HIT=true" >> $GITHUB_ENV
          else
            echo "CACHE_HIT=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: env.CACHE_HIT != 'true'
        run: yarn

      - name: Run tests and generate coverage
        run: npx hardhat coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
